In [11]:
import torch

from torch.nn import functional as F

In [3]:
torch.manual_seed(1)
x = torch.randn(10, 5) + 5

x

tensor([[3.4744, 4.2498, 4.3460, 3.3905, 4.8998],
        [4.3908, 4.0202, 3.3909, 4.2879, 5.3037],
        [4.2227, 4.7485, 4.7777, 6.6871, 5.2284],
        [5.4676, 4.3030, 3.8392, 5.6995, 5.1991],
        [5.8657, 5.2444, 4.3371, 5.8073, 6.1017],
        [4.8241, 2.7544, 3.5535, 5.0612, 4.3823],
        [4.2019, 4.8684, 6.8793, 4.9279, 5.0663],
        [4.5630, 5.7626, 5.4415, 6.1651, 7.0154],
        [5.2152, 4.4758, 4.8140, 4.3554, 6.5392],
        [4.1304, 1.6688, 4.2521, 6.1173, 5.2981]])

In [8]:
_, indices = torch.topk(x, dim=1, k=2)

indices

tensor([[4, 2],
        [4, 0],
        [3, 4],
        [3, 0],
        [4, 0],
        [3, 0],
        [2, 4],
        [4, 3],
        [4, 0],
        [3, 4]])

In [14]:
x * F.one_hot(indices[:, 0]) - x * F.one_hot(indices[:, 1])

tensor([[ 0.0000,  0.0000, -4.3460,  0.0000,  4.8998],
        [-4.3908,  0.0000,  0.0000,  0.0000,  5.3037],
        [ 0.0000,  0.0000,  0.0000,  6.6871, -5.2284],
        [-5.4676,  0.0000,  0.0000,  5.6995,  0.0000],
        [-5.8657,  0.0000,  0.0000,  0.0000,  6.1017],
        [-4.8241,  0.0000,  0.0000,  5.0612,  0.0000],
        [ 0.0000,  0.0000,  6.8793,  0.0000, -5.0663],
        [ 0.0000,  0.0000,  0.0000, -6.1651,  7.0154],
        [-5.2152,  0.0000,  0.0000,  0.0000,  6.5392],
        [ 0.0000,  0.0000,  0.0000,  6.1173, -5.2981]])