In [1]:
import numpy as np

In [64]:
np.random.seed(1)
x = np.random.randn(10, 3)
x[:, 2] = 10*x[:, 2]
x[:, 1] = 5*x[:, 1]

x

array([[  1.62434536,  -3.05878207,  -5.28171752],
       [ -1.07296862,   4.32703815, -23.01538697],
       [  1.74481176,  -3.8060345 ,   3.19039096],
       [ -0.24937038,   7.31053969, -20.60140709],
       [ -0.3224172 ,  -1.92027177,  11.33769442],
       [ -1.09989127,  -0.86214104,  -8.77858418],
       [  0.04221375,   2.91407607, -11.00619177],
       [  1.14472371,   4.5079536 ,   5.02494339],
       [  0.90085595,  -3.4186393 ,  -1.22890226],
       [ -0.93576943,  -1.3394404 ,   5.30355467]])

In [65]:
def act_recon(a):
    
    norm = np.linalg.norm(x, axis=1,keepdims=True)
    
    criteria = norm ** 2 - 2 * a + a**2
    
    criteria = np.mean(criteria, axis=0)
    
    return np.argsort(-criteria)

act_recon(x)

array([2, 1, 0])

In [66]:
def act_recon_greedy(a):
    
    indices = []
    
    d = a.shape[1]
    
    while len(indices) < a.shape[1]:
        
        dimensions = list(set(range(a.shape[1])).difference(indices))
        norms = np.linalg.norm(a[:, dimensions], axis=1)
        
        stats = []
        print("--------")
        
        U = np.eye(d)[:, indices]
        
        a_c = a @ (np.eye(d) - U@U.T)
        for i in dimensions:
            u = np.zeros(d)
            u[i] = 1
            print(u)
            print(a.dot(u), a.dot(u).shape, u.shape)
            norm = np.linalg.norm(a_c - a.dot(u)[:, None]*u)
            print(norm)
            stat = np.mean(norm)
            print(f"[i={i}]: stat={stat}")
            stats.append(stat)
            
            
            
        selected_i = dimensions[np.argmin(stats)]
        print(f"picked={selected_i}")
        indices.append(selected_i)
        
    return indices
act_recon_greedy(x)

--------
[1. 0. 0.]
[ 1.62434536 -1.07296862  1.74481176 -0.24937038 -0.3224172  -1.09989127
  0.04221375  1.14472371  0.90085595 -0.93576943] (10,) (3,)
38.94312409727742
[i=0]: stat=38.94312409727742
[0. 1. 0.]
[-3.05878207  4.32703815 -3.8060345   7.31053969 -1.92027177 -0.86214104
  2.91407607  4.5079536  -3.4186393  -1.3394404 ] (10,) (3,)
37.21614722762934
[i=1]: stat=37.21614722762934
[0. 0. 1.]
[ -5.28171752 -23.01538697   3.19039096 -20.60140709  11.33769442
  -8.77858418 -11.00619177   5.02494339  -1.22890226   5.30355467] (10,) (3,)
12.407421738301629
[i=2]: stat=12.407421738301629
picked=2
--------
[1. 0. 0.]
[ 1.62434536 -1.07296862  1.74481176 -0.24937038 -0.3224172  -1.09989127
  0.04221375  1.14472371  0.90085595 -0.93576943] (10,) (3,)
11.947163139830431
[i=0]: stat=11.947163139830431
[0. 1. 0.]
[-3.05878207  4.32703815 -3.8060345   7.31053969 -1.92027177 -0.86214104
  2.91407607  4.5079536  -3.4186393  -1.3394404 ] (10,) (3,)
3.348045265876324
[i=1]: stat=3.3480452658

[2, 1, 0]

In [46]:
a = np.zeros(2)
b = np.ones(3)

In [52]:
(a[:, None]*b).shape

(2, 3)