In [1]:
import numpy as np 

In [15]:
def first_direction(a, c):
    
    a = a.reshape(1, 2)
    c = c.reshape(1, 2)
    
    mat = a.T @ c + c.T @ a 
    print(mat)
    eigvals, eigvecs = np.linalg.eigh(mat)
    print(eigvals)
    
    return eigvecs[:, -1]

In [16]:
A = np.array([50, 20])
R = np.array([5, 2])
C = R /  A 

C

array([0.1, 0.1])

In [17]:
first_direction(A, C)

[[10.  7.]
 [ 7.  4.]]
[-0.61577311 14.61577311]


array([-0.83484109, -0.55049101])

In [20]:
first_direction(A / np.linalg.norm(A), C / np.linalg.norm(C))

[[1.31306433 0.91914503]
 [0.91914503 0.52522573]]
[-0.08085497  1.91914503]


array([-0.83484109, -0.55049101])

In [18]:
An = A / np.linalg.norm(A)
Rn = R / np.linalg.norm(R)

Cn = Rn / An
An, Cn

(array([0.92847669, 0.37139068]), array([1., 1.]))

In [19]:
first_direction(An, Cn)

[[1.85695338 1.29986737]
 [1.29986737 0.74278135]]
[-0.1143462   2.71408093]


array([-0.83484109, -0.55049101])

In [23]:
Cnb = R / An

Cnb

array([5.38516481, 5.38516481])

In [26]:
first_direction(An, Cnb)

[[10.  7.]
 [ 7.  4.]]
[-0.61577311 14.61577311]


array([-0.83484109, -0.55049101])